[package]
name = "sed-manager-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
sed-manager = { path = "../sed_manager" }
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.41", features = ["full"] }
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rpassword = "7.0"
